[build]
  publish = "public"
  command = "gatsby build"
[context.production]
  environment ={  KONTENT_PROJECT_ID = "b29990e3-7aad-01d1-adab-143f1a1cea98", KONTENT_LANGUAGE_CODENAMES = "default" }
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
